import json
from pathlib import Path
ROOT = Path("/workspace/Kursusoversigt")

providers = [
  {"slug": "itu", "name": "IT-Universitetet i København", "short": "ITU", "website": "https://itu.dk", "city": "København", "description": "Danmarks IT-universitet med forskning og efteruddannelse inden for digitalisering og AI."},
  {"slug": "teknologisk-institut", "name": "Teknologisk Institut", "short": "TI", "website": "https://www.teknologisk.dk", "city": "Taastrup", "description": "Praksisnær efteruddannelse og rådgivning inden for teknologi, innovation og AI."},
  {"slug": "dtu", "name": "Danmarks Tekniske Universitet", "short": "DTU", "website": "https://www.dtu.dk", "city": "Lyngby", "description": "Teknisk universitet med stærke tilbud inden for maskinlæring, data og AI-systemer."},
  {"slug": "ku", "name": "Københavns Universitet", "short": "KU", "website": "https://www.ku.dk", "city": "København", "description": "Bredt universitet med AI-relaterede kurser inden for data science, jura og samfund."},
  {"slug": "cbs", "name": "Copenhagen Business School", "short": "CBS", "website": "https://www.cbs.dk", "city": "København", "description": "Erhvervsorienterede kurser i AI-strategi, ledelse og transformation."},
  {"slug": "au", "name": "Aarhus Universitet", "short": "AU", "website": "https://www.au.dk", "city": "Aarhus", "description": "Forskningstunge AI-kurser og efteruddannelse i Midtjylland."},
  {"slug": "aau", "name": "Aalborg Universitet", "short": "AAU", "website": "https://www.aau.dk", "city": "Aalborg", "description": "Problembaseret læring med fokus på anvendt AI og software."},
  {"slug": "sdu", "name": "Syddansk Universitet", "short": "SDU", "website": "https://www.sdu.dk", "city": "Odense", "description": "AI og data science-kurser med regional forankring i Syddanmark."},
  {"slug": "kea", "name": "Københavns Erhvervsakademi", "short": "KEA", "website": "https://kea.dk", "city": "København", "description": "Praksisnære akademiuddannelser og kurser i digital produktudvikling og AI."},
  {"slug": "dania", "name": "Erhvervsakademi Dania", "short": "Dania", "website": "https://eadania.dk", "city": "Randers", "description": "Efteruddannelse i digitalisering og AI for virksomheder i Jylland."},
  {"slug": "learnai", "name": "LearnAI", "short": "LearnAI", "website": "https://learnai.nu", "city": "Online / DK", "description": "Praksisnære AI-kurser for teams og ledere med fokus på anvendelse i dansk kontekst."},
  {"slug": "ida", "name": "IDA Learning", "short": "IDA", "website": "https://ida.dk", "city": "København", "description": "Efteruddannelse for ingeniører og tekniske specialister, inkl. AI-temaer."},
]

courses = [
  {
    "slug": "itu-ai-for-ledere",
    "title": "AI for ledere",
    "description": "Overblik over generative AI, risici og organisatorisk implementering for beslutningstagere.",
    "provider_slug": "itu",
    "category": "ledelse",
    "level": "begynder",
    "format": "hybrid",
    "location": "København / online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["ledelse", "generativ-ai", "strategi"],
    "source_url": "https://itu.dk/Efteruddannelse",
    "last_verified": "2026-08-15",
  },
  {
    "slug": "itu-machine-learning",
    "title": "Introduktion til machine learning",
    "description": "Grundlæggende supervised learning, evaluering og praktiske pipelines med Python.",
    "provider_slug": "itu",
    "category": "teknisk",
    "level": "mellemniveau",
    "format": "onsite",
    "location": "København",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "5 dage",
    "start_date": None,
    "language": "da",
    "tags": ["machine-learning", "python", "data"],
    "source_url": "https://itu.dk/Efteruddannelse",
    "last_verified": "2026-08-15",
  },
  {
    "slug": "ti-generativ-ai-i-praksis",
    "title": "Generativ AI i praksis",
    "description": "Hands-on kursus i prompt design, RAG og sikker brug af generative modeller i virksomheden.",
    "provider_slug": "teknologisk-institut",
    "category": "praktisk",
    "level": "begynder",
    "format": "onsite",
    "location": "Taastrup",
    "price_dkk": 12900,
    "price_note": None,
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["generativ-ai", "prompting", "rag"],
    "source_url": "https://www.teknologisk.dk",
    "last_verified": "2026-08-20",
  },
  {
    "slug": "ti-ai-projektleder",
    "title": "AI-projektleder",
    "description": "Planlægning, governance og leverance af AI-projekter fra pilot til drift.",
    "provider_slug": "teknologisk-institut",
    "category": "ledelse",
    "level": "mellemniveau",
    "format": "hybrid",
    "location": "Taastrup / online",
    "price_dkk": 15900,
    "price_note": None,
    "duration": "3 dage",
    "start_date": None,
    "language": "da",
    "tags": ["projektledelse", "governance", "roi"],
    "source_url": "https://www.teknologisk.dk",
    "last_verified": "2026-08-20",
  },
  {
    "slug": "ti-computer-vision",
    "title": "Computer vision for industrien",
    "description": "Billedanalyse, kvalitetsinspektion og edge-deployment af vision-modeller.",
    "provider_slug": "teknologisk-institut",
    "category": "teknisk",
    "level": "avanceret",
    "format": "onsite",
    "location": "Aarhus",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "3 dage",
    "start_date": None,
    "language": "da",
    "tags": ["computer-vision", "industri", "edge"],
    "source_url": "https://www.teknologisk.dk",
    "last_verified": "2026-08-12",
  },
  {
    "slug": "dtu-deep-learning",
    "title": "Deep Learning",
    "description": "Neurale netværk, transformers og træning af store modeller med moderne frameworks.",
    "provider_slug": "dtu",
    "category": "teknisk",
    "level": "avanceret",
    "format": "onsite",
    "location": "Lyngby",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "13 uger (deltid)",
    "start_date": None,
    "language": "en",
    "tags": ["deep-learning", "transformers", "python"],
    "source_url": "https://www.dtu.dk",
    "last_verified": "2026-08-10",
  },
  {
    "slug": "dtu-responsible-ai",
    "title": "Responsible AI",
    "description": "Etik, bias, dokumentation og ansvarlig udvikling af AI-systemer.",
    "provider_slug": "dtu",
    "category": "etik",
    "level": "mellemniveau",
    "format": "online",
    "location": "Online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "5 uger",
    "start_date": None,
    "language": "en",
    "tags": ["etik", "bias", "governance"],
    "source_url": "https://www.dtu.dk",
    "last_verified": "2026-08-10",
  },
  {
    "slug": "ku-data-science-intro",
    "title": "Data science og AI — introduktion",
    "description": "Statistik, databehandling og grundlæggende AI-metoder for ikke-programmører.",
    "provider_slug": "ku",
    "category": "data",
    "level": "begynder",
    "format": "hybrid",
    "location": "København / online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "6 uger",
    "start_date": None,
    "language": "da",
    "tags": ["data-science", "statistik", "ai"],
    "source_url": "https://www.ku.dk",
    "last_verified": "2026-08-18",
  },
  {
    "slug": "ku-ai-og-jura",
    "title": "AI, jura og regulering",
    "description": "EU AI Act, persondata og kontraktlige rammer for AI-løsninger i DK/EU.",
    "provider_slug": "ku",
    "category": "jura",
    "level": "mellemniveau",
    "format": "onsite",
    "location": "København",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["ai-act", "gdpr", "jura"],
    "source_url": "https://www.ku.dk",
    "last_verified": "2026-08-18",
  },
  {
    "slug": "cbs-ai-strategy",
    "title": "AI Strategy for Business",
    "description": "Strategisk anvendelse af AI i forretningsmodeller, organisation og konkurrence.",
    "provider_slug": "cbs",
    "category": "ledelse",
    "level": "mellemniveau",
    "format": "onsite",
    "location": "København",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "4 dage",
    "start_date": None,
    "language": "en",
    "tags": ["strategi", "business", "transformation"],
    "source_url": "https://www.cbs.dk",
    "last_verified": "2026-08-14",
  },
  {
    "slug": "cbs-marketing-med-ai",
    "title": "Marketing med AI",
    "description": "Indholdsproduktion, personalisering og måling med generative værktøjer.",
    "provider_slug": "cbs",
    "category": "marketing",
    "level": "begynder",
    "format": "hybrid",
    "location": "København / online",
    "price_dkk": 9800,
    "price_note": None,
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["marketing", "generativ-ai", "content"],
    "source_url": "https://www.cbs.dk",
    "last_verified": "2026-08-14",
  },
  {
    "slug": "au-nlp-dansk",
    "title": "Natural Language Processing",
    "description": "Tekstanalyse, embeddings og sprogmodeller med særligt blik på dansk sprogdata.",
    "provider_slug": "au",
    "category": "teknisk",
    "level": "avanceret",
    "format": "onsite",
    "location": "Aarhus",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "10 uger",
    "start_date": None,
    "language": "en",
    "tags": ["nlp", "sprogmodeller", "dansk"],
    "source_url": "https://www.au.dk",
    "last_verified": "2026-08-11",
  },
  {
    "slug": "au-ai-i-sundhed",
    "title": "AI i sundhedssektoren",
    "description": "Kliniske use cases, datakvalitet og regulatoriske krav til medicinsk AI.",
    "provider_slug": "au",
    "category": "brancher",
    "level": "mellemniveau",
    "format": "hybrid",
    "location": "Aarhus / online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "3 dage",
    "start_date": None,
    "language": "da",
    "tags": ["sundhed", "medicinsk-ai", "regulering"],
    "source_url": "https://www.au.dk",
    "last_verified": "2026-08-11",
  },
  {
    "slug": "aau-applied-ml",
    "title": "Applied Machine Learning",
    "description": "Fra data til produktionsklar model med fokus på MLOps og evaluering.",
    "provider_slug": "aau",
    "category": "teknisk",
    "level": "mellemniveau",
    "format": "onsite",
    "location": "Aalborg",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "5 dage",
    "start_date": None,
    "language": "en",
    "tags": ["mlops", "machine-learning", "produktion"],
    "source_url": "https://www.aau.dk",
    "last_verified": "2026-08-09",
  },
  {
    "slug": "aau-robotics-ai",
    "title": "AI til robotik",
    "description": "Perception, planlægning og learning-based control for industrielle robotter.",
    "provider_slug": "aau",
    "category": "brancher",
    "level": "avanceret",
    "format": "onsite",
    "location": "Aalborg",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "4 dage",
    "start_date": None,
    "language": "en",
    "tags": ["robotik", "perception", "industri"],
    "source_url": "https://www.aau.dk",
    "last_verified": "2026-08-09",
  },
  {
    "slug": "sdu-ai-fundamentals",
    "title": "AI Fundamentals",
    "description": "Begreber, værktøjer og realistiske forventninger til AI i organisationer.",
    "provider_slug": "sdu",
    "category": "praktisk",
    "level": "begynder",
    "format": "online",
    "location": "Online",
    "price_dkk": 4500,
    "price_note": None,
    "duration": "4 uger",
    "start_date": None,
    "language": "da",
    "tags": ["fundamentals", "overblik", "organisation"],
    "source_url": "https://www.sdu.dk",
    "last_verified": "2026-08-16",
  },
  {
    "slug": "sdu-dataetik",
    "title": "Dataetik og AI",
    "description": "Etiske dilemmaer, fairness og organisatorisk ansvar i data-drevne beslutninger.",
    "provider_slug": "sdu",
    "category": "etik",
    "level": "begynder",
    "format": "hybrid",
    "location": "Odense / online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["etik", "fairness", "ansvar"],
    "source_url": "https://www.sdu.dk",
    "last_verified": "2026-08-16",
  },
  {
    "slug": "kea-prompt-engineering",
    "title": "Prompt engineering for praktikere",
    "description": "Systematisk prompting, evaluering af outputs og integrationsmønstre i workflows.",
    "provider_slug": "kea",
    "category": "praktisk",
    "level": "begynder",
    "format": "onsite",
    "location": "København",
    "price_dkk": 6900,
    "price_note": None,
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["prompting", "workflows", "produktivitet"],
    "source_url": "https://kea.dk",
    "last_verified": "2026-08-21",
  },
  {
    "slug": "kea-ai-produktudvikling",
    "title": "AI i produktudvikling",
    "description": "Brugertests, prototyper og MVP-design for AI-features i digitale produkter.",
    "provider_slug": "kea",
    "category": "produkt",
    "level": "mellemniveau",
    "format": "hybrid",
    "location": "København / online",
    "price_dkk": 8900,
    "price_note": None,
    "duration": "3 dage",
    "start_date": None,
    "language": "da",
    "tags": ["produkt", "ux", "mvp"],
    "source_url": "https://kea.dk",
    "last_verified": "2026-08-21",
  },
  {
    "slug": "dania-digital-transformation",
    "title": "Digital transformation med AI",
    "description": "Kortlægning af processer, use case-prioritering og forandringsledelse.",
    "provider_slug": "dania",
    "category": "ledelse",
    "level": "begynder",
    "format": "onsite",
    "location": "Randers",
    "price_dkk": 7500,
    "price_note": None,
    "duration": "3 dage",
    "start_date": None,
    "language": "da",
    "tags": ["transformation", "processer", "forandring"],
    "source_url": "https://eadania.dk",
    "last_verified": "2026-08-13",
  },
  {
    "slug": "dania-chatgpt-for-kontoret",
    "title": "ChatGPT og AI på kontoret",
    "description": "Praktisk brug af generative værktøjer til administration, mail og dokumenter.",
    "provider_slug": "dania",
    "category": "praktisk",
    "level": "begynder",
    "format": "online",
    "location": "Online",
    "price_dkk": 3200,
    "price_note": None,
    "duration": "1 dag",
    "start_date": None,
    "language": "da",
    "tags": ["chatgpt", "kontor", "produktivitet"],
    "source_url": "https://eadania.dk",
    "last_verified": "2026-08-13",
  },
  {
    "slug": "learnai-team-workshop",
    "title": "AI-workshop for teams",
    "description": "Faciliteret workshop hvor teamet finder og afprøver AI-use cases på egne opgaver.",
    "provider_slug": "learnai",
    "category": "praktisk",
    "level": "begynder",
    "format": "hybrid",
    "location": "Danmark / online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "1 dag",
    "start_date": None,
    "language": "da",
    "tags": ["workshop", "teams", "use-cases"],
    "source_url": "https://learnai.nu",
    "last_verified": "2026-08-25",
  },
  {
    "slug": "learnai-lederkursus",
    "title": "AI for danske ledere",
    "description": "Beslutningsrammer, risici og konkrete næste skridt for ledere uden teknisk baggrund.",
    "provider_slug": "learnai",
    "category": "ledelse",
    "level": "begynder",
    "format": "online",
    "location": "Online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "2 sessioner",
    "start_date": None,
    "language": "da",
    "tags": ["ledelse", "strategi", "risici"],
    "source_url": "https://learnai.nu",
    "last_verified": "2026-08-25",
  },
  {
    "slug": "ida-python-til-ai",
    "title": "Python til AI",
    "description": "Python-basics, datahåndtering og første ML-modeller for tekniske specialister.",
    "provider_slug": "ida",
    "category": "teknisk",
    "level": "begynder",
    "format": "onsite",
    "location": "København",
    "price_dkk": 8500,
    "price_note": None,
    "duration": "3 dage",
    "start_date": None,
    "language": "da",
    "tags": ["python", "machine-learning", "data"],
    "source_url": "https://ida.dk",
    "last_verified": "2026-08-17",
  },
  {
    "slug": "ida-llm-integration",
    "title": "LLM-integration for udviklere",
    "description": "API-integration, evaluation, sikkerhed og omkostningsstyring for LLM-apps.",
    "provider_slug": "ida",
    "category": "teknisk",
    "level": "avanceret",
    "format": "hybrid",
    "location": "København / online",
    "price_dkk": 11900,
    "price_note": None,
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["llm", "api", "udvikling"],
    "source_url": "https://ida.dk",
    "last_verified": "2026-08-17",
  },
  {
    "slug": "dtu-mlops",
    "title": "MLOps",
    "description": "CI/CD for modeller, monitoring, feature stores og drift i cloud/on-prem.",
    "provider_slug": "dtu",
    "category": "teknisk",
    "level": "avanceret",
    "format": "online",
    "location": "Online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "8 uger",
    "start_date": None,
    "language": "en",
    "tags": ["mlops", "devops", "monitoring"],
    "source_url": "https://www.dtu.dk",
    "last_verified": "2026-08-10",
  },
  {
    "slug": "ti-ai-i-produktion",
    "title": "AI i produktionsvirksomheder",
    "description": "Predictive maintenance, processoptimering og datafangst på fabriksgulvet.",
    "provider_slug": "teknologisk-institut",
    "category": "brancher",
    "level": "mellemniveau",
    "format": "onsite",
    "location": "Taastrup",
    "price_dkk": 13900,
    "price_note": None,
    "duration": "2 dage",
    "start_date": None,
    "language": "da",
    "tags": ["produktion", "iot", "predictive"],
    "source_url": "https://www.teknologisk.dk",
    "last_verified": "2026-08-20",
  },
  {
    "slug": "ku-sprogmodeller",
    "title": "Store sprogmodeller — et kritisk overblik",
    "description": "Hvordan LLM'er virker, begrænsninger, hallucinationer og samfundsmæssige konsekvenser.",
    "provider_slug": "ku",
    "category": "etik",
    "level": "begynder",
    "format": "online",
    "location": "Online",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "4 uger",
    "start_date": None,
    "language": "da",
    "tags": ["llm", "kritik", "samfund"],
    "source_url": "https://www.ku.dk",
    "last_verified": "2026-08-18",
  },
  {
    "slug": "cbs-ai-governance",
    "title": "AI Governance Board Crash Course",
    "description": "Bestyrelses- og direktionsoverblik: risici, rapportering og tilsyn med AI.",
    "provider_slug": "cbs",
    "category": "ledelse",
    "level": "avanceret",
    "format": "onsite",
    "location": "København",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "1 dag",
    "start_date": None,
    "language": "da",
    "tags": ["governance", "bestyrelse", "risiko"],
    "source_url": "https://www.cbs.dk",
    "last_verified": "2026-08-14",
  },
  {
    "slug": "au-reinforcement-learning",
    "title": "Reinforcement Learning",
    "description": "Markov decision processes, policy gradients og anvendelser i kontrol og anbefaling.",
    "provider_slug": "au",
    "category": "teknisk",
    "level": "avanceret",
    "format": "onsite",
    "location": "Aarhus",
    "price_dkk": None,
    "price_note": "Ukendt — se udbyder",
    "duration": "8 uger",
    "start_date": None,
    "language": "en",
    "tags": ["reinforcement-learning", "kontrol", "algoritmer"],
    "source_url": "https://www.au.dk",
    "last_verified": "2026-08-11",
  },
]

# Enrich courses with provider name
prov_map = {p["slug"]: p for p in providers}
for c in courses:
    p = prov_map[c["provider_slug"]]
    c["provider_name"] = p["name"]
    c["provider_short"] = p["short"]

(ROOT / "src" / "data" / "providers.json").write_text(
    json.dumps(providers, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)
(ROOT / "src" / "data" / "courses.json").write_text(
    json.dumps(courses, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)
print(f"providers={len(providers)} courses={len(courses)}")
